//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Myresouce) DeepCopyInto(out *Myresouce) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Myresouce.
func (in *Myresouce) DeepCopy() *Myresouce {
	if in == nil {
		return nil
	}
	out := new(Myresouce)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Myresouce) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MyresouceList) DeepCopyInto(out *MyresouceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Myresouce, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MyresouceList.
func (in *MyresouceList) DeepCopy() *MyresouceList {
	if in == nil {
		return nil
	}
	out := new(MyresouceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MyresouceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MyresouceSpec) DeepCopyInto(out *MyresouceSpec) {
	*out = *in
	if in.SecondNum != nil {
		in, out := &in.SecondNum, &out.SecondNum
		*out = new(int)
		**out = **in
	}
	if in.FirstNum != nil {
		in, out := &in.FirstNum, &out.FirstNum
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MyresouceSpec.
func (in *MyresouceSpec) DeepCopy() *MyresouceSpec {
	if in == nil {
		return nil
	}
	out := new(MyresouceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MyresouceStatus) DeepCopyInto(out *MyresouceStatus) {
	*out = *in
	if in.LastUpdatedc != nil {
		in, out := &in.LastUpdatedc, &out.LastUpdatedc
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MyresouceStatus.
func (in *MyresouceStatus) DeepCopy() *MyresouceStatus {
	if in == nil {
		return nil
	}
	out := new(MyresouceStatus)
	in.DeepCopyInto(out)
	return out
}
